openapi: 3.0.3
info:
  title: Pillar 2 API
  description: An API for managing and retrieving data in accordance with Pillar 2 tax rules.
paths:
  /uk-tax-return:
    post:
      summary: SubmitUKTR
      description: |
        Submits a UK Tax Return for a specified accounting period.
        ### Error Codes
        <p>This table contains a list of 422 error codes returned when a SubmitUKTR or AmendUKTR API request is not processed successfully. Error codes still in development are marked as "awaiting clarification".</p>
        <table>
        <thead>
        <tr>
        <th>Error Message</th>
        <th>Next Steps</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td>002 - Pillar 2 ID (SAP Number) is missing or invalid</td>
        <td>Please provide the request header for your client, to check it contains the Pillar 2 ID (SAP Number) they were assigned at registration.</td>
        </tr>
        <tr>
        <td>003 - Request could not be processed</td>
        <td>The message could not be processed due to locking. Please check if there is currently an open enquiry on your tax account.</td>
        </tr>
        <tr>
        <td>044 - Tax Obligation Already Fulfilled</td>
        <td>A UKTR for the specified period has already been submitted. If you are trying to amend a UKTR, please check you are sending the <em>amendUKTR</em> API request.</td>
        </tr>
        <tr>
        <td>063 - Business Partner does not have an Active Pillar 2 Subscription</td>
        <td>The Pillar 2 ID (SAP Number) in the request header is not listed as active by HMRC for this regime. Please contact the central support team.</td>
        </tr>
        <tr>
        <td>093 - Invalid Return</td>
        <td>There is an error with the tax return you’ve submitted in the request. Please check the <em>accountingPeriodFrom</em> and <em>accountingPeriodTo</em> fields to ensure the dates are valid. If you need to check or amend the accounting period pattern, you can do this on the Pillar 2 site under “Personal Details”.</td>
        </tr>
        <tr>
        <td>094 - Invalid DTT Election</td>
        <td>The DTT values in the request are invalid. Please complete the following checks, then submit the request again. If <em>electionDTTSingleMember</em> is true, the <em>numberSubGroupDTT</em> should be greater than 0. This number represents the number of liable entities that owe a DTT amount greater than 0. The total number of liable entities who owe DTT in the payload should be the same as the number in <em>numberSubGroupDTT</em>.</td>
        </tr>
        <tr>
        <td>095 - Invalid UTPR Election</td>
        <td>The UTPR values in the request are invalid. Please complete the following checks, then submit the request again. If <em>electionUTPRSingleMember</em> is true, the <em>numberSubGroupUTPR</em> should be greater than 0. This number represents the number of liable entities that owe a UTPR amount greater than 0. The total number of liable entities who owe UTPR in the payload should be the same as the number in <em>numberSubGroupUTPR</em>.</td>
        </tr>
        <tr>
        <td>096 - Invalid Total Liability</td>
        <td>The <em>totalLiability</em> value in the request does not match the combined values of <em>totalLiabilityDTT</em>, <em>totalLiabilityIIR</em> and <em>totalLiabilityUTPR</em>. Please check the sum of these fields matches the <em>totalLiability</em> value and submit the request again.</td>
        </tr>
        <tr>
        <td>097 - Invalid Total Liability IIR</td>
        <td>The <em>totalLiabilityIIR</em> value does not match the <em>amountIIR value</em> from the <em>liableEntities</em> array. Please check the value of these fields matches and submit the request again.</td>
        </tr>
        <tr>
        <td>098 - Invalid Total Liability DTT</td>
        <td>The <em>totalLiabilityDTT</em> value does not match the <em>amountDTT</em> value from the <em>liableEntities</em> array. Please check the value of these fields matches and submit the request again.</td>
        </tr>
        <tr>
        <td>099 - Invalid Total Liability UTPR</td>
        <td>The <em>totalLiabilityUTPR</em> value does not match the <em>amountUTPR</em> value from the <em>liableEntities</em> array. Please check the value of these fields matches and submit the request again.</td>
        </tr>
        </tbody>
        </table>
      requestBody:
        content:
          application/json:
            examples:
              NilReturnsMneAndUk:
                $ref: "#/components/examples/requests.UKTRNilReturnsMneAndUk"
              NilReturnsDomesticOnlyWithUkGaap:
                $ref: "#/components/examples/requests.UKTRNilReturnsDomesticOnlyWithUkGaap"
              NilReturnsDomesticOnlyWithoutUkGaap:
                $ref: "#/components/examples/requests.UKTRNilReturnsDomesticOnlyWithoutUkGaap"
              LiabilityReturnsMneAndUkOneEntity:
                $ref: "#/components/examples/requests.UKTRLiabilityReturnsMneAndUkWithOneEntity"
              LiabilityReturnsMneAndUkTwoEntities:
                $ref: "#/components/examples/requests.UKTRLiabilityReturnsMneAndUkWithTwoEntities"
              LiabilityReturnsDomesticOneEntityUkGaap:
                $ref: "#/components/examples/requests.UKTRLiabilityReturnsDomesticOnlyOneEntityAndUkGaap"
              LiabilityReturnsDomesticTwoEntities:
                $ref: "#/components/examples/requests.UKTRLiabilityReturnsDomesticOnlyTwoEntities"       
      responses:
        "201":
          description: UK Tax Return Submission Created
          content:
            application/json:
              examples:
                responses.UKTRSuccessResponseExample:
                  $ref: "#/components/examples/responses.UKTRSuccessResponseExample"
      security:
        - userRestricted: [write:pillar2]
    put:
      summary: AmendUKTR
      description: |
        Amends a UK tax return submitted for a specified accounting period.   
        
        ### Error Codes
        <p>AmendUKTR generates the same error codes as Submit UKTR, please use the Error Codes table in the SubmitUKTR section above.</p>
      requestBody:
        content:
          application/json:
            examples:
              NilReturnsMneAndUk:
                $ref: "#/components/examples/requests.UKTRNilReturnsMneAndUk"
              NilReturnsDomesticOnlyWithUkGaap:
                $ref: "#/components/examples/requests.UKTRNilReturnsDomesticOnlyWithUkGaap"
              NilReturnsDomesticOnlyWithoutUkGaap:
                $ref: "#/components/examples/requests.UKTRNilReturnsDomesticOnlyWithoutUkGaap"
              LiabilityReturnsMneAndUkOneEntity:
                $ref: "#/components/examples/requests.UKTRLiabilityReturnsMneAndUkWithOneEntity"
              LiabilityReturnsMneAndUkTwoEntities:
                $ref: "#/components/examples/requests.UKTRLiabilityReturnsMneAndUkWithTwoEntities"
              LiabilityReturnsDomesticOneEntityUkGaap:
                $ref: "#/components/examples/requests.UKTRLiabilityReturnsDomesticOnlyOneEntityAndUkGaap"
              LiabilityReturnsDomesticTwoEntities:
                $ref: "#/components/examples/requests.UKTRLiabilityReturnsDomesticOnlyTwoEntities"
      responses:
        "200":
          description: UK Tax Return Submission Updated
          content:
            application/json:
              examples:
                responses.UKTRSuccessResponseExample:
                  $ref: "#/components/examples/responses.UKTRSuccessResponseExample"
      security:
        - userRestricted: [write:pillar2]
  /below-threshold-notification:
    post:
      summary: SubmitBTN
      description: |
        Submits a Below-Threshold Notification for a specified accounting period when the group no longer meets the threshold for the Pillar 2 top-up tax.
        ### Error Codes
        <p>This table contains a list of 422 error codes returned when a SubmitBTN API request is not processed successfully.</p>
        <table>
        <thead>
        <tr>
        <th>Error Message</th>
        <th>Next Steps</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td>002 - Pillar2 ID (SAP Number) is missing or invalid</td>
        <td>Please provide the request header for your client, to check it contains the Pillar 2 ID (SAP Number) they were assigned at registration.</td>
        </tr>
        <tr>
        <td>003 - Request could not be processed</td>
        <td>The message could not be processed due to locking. Please check if there is currently an open enquiry on your tax account.</td>
        </tr>
        <tr>
        <td>044 - Tax Obligation already fulfilled</td>
        <td>A BTN for the specified period has already been submitted.</td>
        </tr>
        <tr>
        <td>063 - Business Partner does not have an Active Pillar 2 Subscription</td>
        <td>The Pillar 2 ID (SAP Number) in the request header is not listed as active by HMRC for this regime. Please contact the central support team.</td>
        </tr>
        </tbody>
        </table>
      requestBody:
        content:
          application/json:
            examples:
              requests.BTNRequestExample:
                $ref: "#/components/examples/requests.BTNRequestExample"
      responses:
        "201":
          description: Below-Threshold Notification Submission Created
          content:
            application/json:
              examples:
                responses.BTNSuccessResponseExample:
                  $ref: "#/components/examples/responses.BTNSuccessResponseExample"
      security:
        - userRestricted: [write:pillar2]
  /obligations-and-submissions:
    get:
      summary: Retrieve Obligations and Submissions
      description: |
        Retrieves the Obligations and Submissions for an accounting period.
        ### Error Codes
        <p>This table contains a list of 422 error codes returned when a Obligations and Submissions API request is not processed successfully.</p>
        <table>
        <thead>
        <tr>
        <th>Error Message</th>
        <th>Next Steps</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td>002 - Pillar2 ID (SAP Number) is missing or invalid</td>
        <td>Please provide the request header for your client, to check it contains the Pillar 2 ID (SAP Number) they were assigned at registration.</td>
        </tr>
        <tr>
        <td>003 - Request could not be processed</td>
        <td>The message could not be processed due to locking. Please check if there is currently an open enquiry on your tax account.</td>
        </tr>
        <tr>
        <td>025 - No associated data found</td>
        <td>No associated data found for this Pillar 2 ID.</td>
        </tr>
        <tr>
        </tbody>
        </table>
      security:
        - userRestricted: [write:pillar2]
  /setup/organisation:
    post:
      summary: Create Test Organisation
      description: |
        Creates a test organisation associated with your authed organisation.
      security:
        - userRestricted: [write:pillar2]
    get:
      summary: Get Test Organisation
      description: |
        Gets a test organisation associated with your authed organisation.
      security:
        - userRestricted: [read:pillar2]
    put:
      summary: Update Test Organisation
      description: |
        Updates a test organisation associated with your authed organisation.
      security:
        - userRestricted: [write:pillar2]
    delete:
      summary: Delete Test Organisation
      description: |
        Deletes a test organisation associated with your authed organisation.
      security:
        - userRestricted: [write:pillar2]

components:

  examples:
    requests.BTNRequestExample:
      summary: "Request example"
      value:
        accountingPeriodFrom: "2024-01-01"
        accountingPeriodTo: "2024-12-31"

    responses.BTNSuccessResponseExample:
      summary: "Success response"
      value:
        processingDate: "2026-06-26T09:26:17Z"

    #mne and uk
    requests.UKTRNilReturnsMneAndUk:
      summary: "Nil Returns - MNE and UK"
      value:
        accountingPeriodFrom: "2024-01-01"
        accountingPeriodTo: "2024-12-31"
        obligationMTT: true
        electionUKGAAP: false
        liabilities:
          returnType: "NIL_RETURN"


    #nil returns - domestic only w/ uk gaap
    requests.UKTRNilReturnsDomesticOnlyWithUkGaap:
      summary: "Nil Returns - Domestic Only with UK GAAP"
      value:
        accountingPeriodFrom: "2024-01-01"
        accountingPeriodTo: "2024-12-31"
        obligationMTT: false
        electionUKGAAP: true
        liabilities:
          returnType: "NIL_RETURN"

    #nil returns - domestic only w/o uk gaap
    requests.UKTRNilReturnsDomesticOnlyWithoutUkGaap:
      summary: "Nil Returns - UK Only without UK GAAP"
      value:
        accountingPeriodFrom: "2024-01-01"
        accountingPeriodTo: "2024-12-31"
        obligationMTT: false
        electionUKGAAP: false
        liabilities:
          returnType: "NIL_RETURN"

    #liability returns - mne and uk w/ 1 entity
    requests.UKTRLiabilityReturnsMneAndUkWithOneEntity:
      summary: "Liability Returns - MNE and UK with 1 Entity"
      value:
        accountingPeriodFrom: "2025-04-06"
        accountingPeriodTo: "2026-04-05"
        obligationMTT: true
        electionUKGAAP: false
        liabilities:
          electionDTTSingleMember: false
          electionUTPRSingleMember: false
          numberSubGroupDTT: 4
          numberSubGroupUTPR: 5
          totalLiability: 14401.49
          totalLiabilityDTT: 5000.99
          totalLiabilityIIR: 3400
          totalLiabilityUTPR: 6000.5
          liableEntities:
            - ukChargeableEntityName: "Newco PLC"
              idType: "CRN"
              idValue: "12345678"
              amountOwedDTT: 5000.99
              amountOwedIIR: 3400
              amountOwedUTPR: 6000.5


    #liability returns - mne and uk w/ 2 entities
    requests.UKTRLiabilityReturnsMneAndUkWithTwoEntities:
      summary: "Liability Returns - MNE and UK with 2 Entities"
      value:
        accountingPeriodFrom: "2025-04-06"
        accountingPeriodTo: "2026-04-05"
        obligationMTT: true
        electionUKGAAP: false
        liabilities:
          electionDTTSingleMember: false
          electionUTPRSingleMember: false
          numberSubGroupDTT: 4
          numberSubGroupUTPR: 5
          totalLiability: 49401.49
          totalLiabilityDTT: 35000
          totalLiabilityIIR: 5400
          totalLiabilityUTPR: 9001.49
          liableEntities:
            - ukChargeableEntityName: "Newco PLC"
              idType: "CRN"
              idValue: "12345678"
              amountOwedDTT: 5000
              amountOwedIIR: 3400
              amountOwedUTPR: 6000.5
            - ukChargeableEntityName: "Conew PLC"
              idType: "CT-UTR"
              idValue: "1234567890"
              amountOwedDTT: 30000
              amountOwedIIR: 2000
              amountOwedUTPR: 3000.99

    #liability returns - uk only - domestic flag, 1 entity and uk gaap
    requests.UKTRLiabilityReturnsDomesticOnlyOneEntityAndUkGaap:
      summary: "Liability Returns - Domestic Only with 1 Entity and UK GAAP"
      value:
        accountingPeriodFrom: "2025-01-01"
        accountingPeriodTo: "2026-12-31"
        obligationMTT: false
        electionUKGAAP: true
        liabilities:
          electionDTTSingleMember: false
          electionUTPRSingleMember: false
          numberSubGroupDTT: 4
          numberSubGroupUTPR: 5
          totalLiability: 26567.89
          totalLiabilityDTT: 26567.89
          liableEntities:
            - ukChargeableEntityName: "Conew PLC"
              idType: "CT-UTR"
              idValue: "9765678990"
              amountOwedDTT: 26567.89

    #liability returns - uk only - domestic flag, 2 entities
    requests.UKTRLiabilityReturnsDomesticOnlyTwoEntities:
      summary: "Liability Returns - Domestic Only with 2 Entities"
      value:
        accountingPeriodFrom: "2025-04-06"
        accountingPeriodTo: "2026-04-05"
        obligationMTT: false
        electionUKGAAP: false
        liabilities:
          electionDTTSingleMember: false
          electionUTPRSingleMember: false
          numberSubGroupDTT: 4
          numberSubGroupUTPR: 5
          totalLiability: 26567.89
          totalLiabilityDTT: 26567.89
          liableEntities:
            - ukChargeableEntityName: "Newco PLC"
              idType: "CRN"
              idValue: "12345679"
              amountOwedDTT: 4567
            - ukChargeableEntityName: "Conew PLC"
              idType: "CT-UTR"
              idValue: "9765678990"
              amountOwedDTT: 22000.89

    responses.UKTRSuccessResponseExample:
      summary: "Success response"
      value:
        processingDate: "2026-06-26T09:26:17Z"
        formBundleNumber: "119000004320"

    responses.UKTRNilReturnResponseExample:
      summary: "Request example for Domestic only with UK GAAP Nil Return"
      value:
        accountingPeriodFrom: "2024-01-01"
        accountingPeriodTo: "2024-12-31"
        obligationMTT: false
        electionUKGAAP: true
        liabilities:
          returnType: "NIL_RETURN"

  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        Please see the [developer hub](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) for more details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:pillar2: Read data related to Pillar2 subscription
            write:pillar2: Write data related to Pillar2 subscription
